### ISSUE TITLE
Laravel 11 compatibility

### ISSUE THREAD

**Issue by bucari** [hmones/laravel-digest#15]
Hi @hmones,
i can't install laravel-digest on Laravel 11

composer require hmones/laravel-digest returns this error

Problem 1
    - hmones/laravel-digest[v1.0.0, v2.0.0] require illuminate/support ~7|~8 -> found illuminate/support[v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - hmones/laravel-digest[v2.1.0, ..., v2.1.2] require illuminate/support ~7|~8|~9 -> found illuminate/support[v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16] but these were not loaded, likely because it conflicts with another require.
    - hmones/laravel-digest v2.2.0 requires illuminate/support ~7|~8|~9|~10 -> found illuminate/support[v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.8] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires hmones/laravel-digest * -> satisfiable by hmones/laravel-digest[v1.0.0, v2.0.0, ..., v2.2.0].

You can also try re-running composer require with an explicit version constraint, e.g. "composer require hmones/laravel-digest:*" to figure out if any version is installable, or "composer require hmones/laravel-digest:^2.1" if you know which you need.

**Comment by hmones** [comment]
Thanks for pointing this out. So far, I haven't implemented the upgrade for Laravel 11, but I'll be working on it and will keep you posted!

**Comment by hmones** [comment]
@bucari I've published a new release now that supports laravel 11 :tada: (v2.3.0), please try again and it should be working fine.
Thanks for highlighting this :+1:
