### ISSUE TITLE
Possible error in docs

### ISSUE THREAD

**Issue by dr-codswallop** [hmones/laravel-digest#7]
Hey, looks like a great package. Just wondering if there's a typo in the usage example code for the observer?

Step 4: `$frequency = 'custom';`

If the example is to trigger after each 10th user registration, should this instead be  `$frequency = '10';`

**Comment by hmones** [comment]
you're absolutely right, I'll fix it. Thanks for pointing this out

**Comment by hmones** [comment]
#9 Fixed README file and publishing of configuration files
